title: ShatCode Blog
author: ShatCode
description: My own hacking blog
google_analytics:
google_site_verification_content: 
disqus_forum_shortname: shatcode-github-io

#Usernames and badges
htb_badge_no:
thm_badge_no:
show_thm_htb_badges_in_nav: false
github_username: ShatCode
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: rinish-sam
twitch:
youtube:
twitter: ShatCode
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
